steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'sample-cluster', '--zone=us-central1-a', '--project=final-task-322012']
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', 'final-task-image']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'final-task-image', 'gcr.io/final-task-322012/fina-task']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/final-task-322012/fina-task']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/final-task-app', 'fina-task=gcr.io/final-task-322012/fina-task:latest']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=sample-cluster'