apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-task-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: final-task-app
  template:
    metadata:
      labels:
        run: final-task-app
    spec:
      containers:
        - name: task-image
          image: us-central1-docker.pkg.dev/final-challenge-323609/artifacts-repo/task-image:latest
          ports:
            - containerPort: 8080