apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-task-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: final-task-app
  template:
    metadata:
      labels:
        run: final-task-app
    spec:
      containers:
        - name: fina-task
          image: gcr.io/final-task-322012/fina-task:0.1
          ports:
            - containerPorts: 8080